# Define the following to 1 to enable build
BENCH_GTC_MPI = 1
BENCH_CHARGEI_PTHREADS = 0
BENCH_PUSHI_PTHREADS = 0
BENCH_SERIAL = 0

CC = mpixlc_r
MPICC = mpixlc_r
CFLAGS = -DUSE_MPI=1 
CFLAGSOMP =
COPTFLAGS = -O0 -qsmp=omp:noopt:noauto -qfloat=nofold
CDEPFLAGS = 
CLDFLAGS = 
MPIDIR = 
CFLAGS  +=


EXEEXT = _vesta_debug_mpi

AR = ar
ARCRFLAGS = cr
RANLIB = ranlib
